### ISSUE TITLE
Image files presented in random or reverse order (w/ View all, as well as Next File)

### ISSUE THREAD

**Issue by juliamiller** [nabu-catalog/nabu#603] opened 2016-10-10 04:27 UTC
Collections which have many image files (PK2, LRB3- Notebooks, etc) have file names that reflect the order in which the images should be viewed. This ordering is not reflected using two methods of image viewing.
1. (REVERSE ORDER) Clicking on the 1st image in PK2, Item 13: PK2-13-PIXBIAB01.jpg does not have the option to press Next file to view ...02. The only button available to press in Previous file which then goes to ...02 (this is not random, clearly, but backwards). The same thing occurs with the View All option. Even the thumbnails are in this reversed order, despite the items being presented in the correct order in the list view.
2. (RANDOM ORDER) When looking at the images in LRB3, item NB13, you can click to view the image ...001, and this time you are presented with the Next file button, but the order is 001, 043, 117, 101, etc. When you click on View all, the order is further shuffled, including the thumbnails. The order of the files presented in the item list view is correct.

**Comment by JonoGillett** [comment] 2016-10-27 04:15
This looks like a duplicate of Issue #596 - can you see anything different between them?

**Comment by juliamiller** [comment] 2016-10-27 21:27
No, I did not catch Nick's previous issue. I suppose this description has more detail, but essentially it is the same issue.

**Closed** 2016-11-01 05:43 UTC
Labels: 2016 Priorities, Urgent (#2)

**Comment by juliamiller** [comment] 2019-01-13 21:40
@JonoGillett Just wondering what the update is on this. I will be sending notebook images for IF01 and would like to show the depositor how to use the viewer, but it is still not functioning properly. Files still presented in a random order. Additionally, there is no file name on the image viewer page, so unless there is a page number shown in the image itself, one has no idea where the image falls in the list of files. The issue that was mentioned as being a duplicate one has bee closed.
