### ISSUE TITLE
Merge users

### ISSUE THREAD

**Issue by jangari** [nabu-catalog/nabu#384] opened 2014-10-23 02:33 UTC
This is brought up by #380.

In cases where there are two entries in the users table for a single person, one created by the user creating an account and the other created by metadata import, there should be a means to merge them into a single account. I'm thinking of Gmail's merge contacts function.

**Comment by JonoGillett** [comment] 2015-03-12 00:43
Could someone run me through the workflow of how this should behave? I've created an initial mechanism for admins to selectively merge same-name users together (and have all items re-assigned to the primary user) but I'd like to hear how the end users would expect it to work

**Comment by jangari** [comment] 2015-03-12 23:08
This is probably very difficult to achieve, but would be ideal:

1. In admin/users page, admin clicks 'edit' on an entry.
2. Button at bottom that says "merge with another user"
3. Opens dialogue to select user to merge the current user with another user (which shows name and email for disambiguation)
4. Shows both user records side-by-side and warns if any fields will be overwritten (if both records have an email address, for example)
5. User may select one record to be 'primary' and thus that the non-primary record will be effectively deleted (unless it contains information in any fields that the primary record does not have).
6. All database references to the non-primary record should then be updated to point instead to the primary record.

A user-case might be as follows.

Eric Coat has a collection that his research assistant has accessioned into the system. The RA creates a 'user', called Eric Coat (let's say this record is number 45), whom they reference in all the items, and for the collection in general, as the collector/recordist, whatever.
Some time later, Eric himself decides he would like to see his recordings or possibly update his metadata. So he goes to the website and is eventually prompted to create an account. He does so under his name (which creates record 73). As far as the system knows, the records 45 and 73 are totally unrelated, and coincidentally have the same information in the firstname and lastname fields.
Eric contacts us as he is unable to modify the metadata on his collection (of course he can't; he's just some user according to the system). 
We see his account and acknowledge that he is indeed the Eric Coat, and that in effect, user 45 and 73 are the same person, so we merge information from one record into the other (direction is irrelevant I would assume, but let's say record 45 is merged into record 73), and any collections that point to record 45 as collector/recordist or whatever, are updated to point instead to record 73.

Sorry if the above is terribly verbose.

**Comment by JonoGillett** [comment] 2015-03-12 23:58
That description is precisely what I was after, thanks! Funnily enough I implemented almost exactly that.

The only point of difference is how the duplicate user is selected. Currently I have it giving you a selectable list of users where the first and last name are the same. It provides id, name and email address for differentiation. This way you can merge 2 or more accounts.

I can modify it to allow you to select users with different names if that is likely to be a use case. This might be handy if, for example, a user has an account under a shortened name or a misspelt name.

Some screens of my current version, for illustration:

If an admin views the user page, and there are multiple users with the same name (the link takes you to the admin seciton):
![image](https://cloud.githubusercontent.com/assets/10914573/6630627/3439d476-c96f-11e4-85ec-bb659bf4c1e1.png)

The admin screen - you select from the possible details of all merge-able users and choose which ones to delete and merge:
![image](https://cloud.githubusercontent.com/assets/10914573/6630678/a1699efa-c96f-11e4-8937-eda1002ff25d.png)

**Comment by jangari** [comment] 2015-03-13 00:43
> I can modify it to allow you to select users with different names if that is likely to be a use case. This might be handy if, for example, a user has an account under a shortened name or a misspelt name.

Yes, I think it is currently the case that some duplicate accounts have differing names, some due to shortenings, misspellings, etc.,

Thanks! That looks great!

**Comment by nthieberger** [comment] 2015-03-18 06:12
Does it then replace all references in the bataset to the deleted use and replace them with the combined user?

**Comment by JonoGillett** [comment] 2015-03-18 07:34
Yes, it currently looks up all records pointing at the duplicates and
reassigns them to the primary user.

Does it then replace all references in the bataset to the deleted use and
replace them with the combined user?

—
Reply to this email directly or view it on GitHub
<https://github.com/nabu-catalog/nabu/issues/384#issuecomment-82767305>.

**Comment by nthieberger** [comment] 2015-05-06 04:07
I just tried merging two users and it generated an error

**Comment by JonoGillett** [comment] 2015-05-06 04:34
I just happened to notice this in Rollbar about a minute before you posted this, I think the issue is because they both had the same permissions on an item (item agent / item admin as the models are called) and then the merge attempted to create that same permission by changing the user.

e.g.
Al Shultz was an item agent on item 5, and Albert Shultz was an item agent on item 5.
Merge comes along and tries to assign Al's permissions to Albert, thus leaving us with:
Albert Shultz was an item agent on item, and Albert Shultz was an item agent on item 5.
But this isn't allowed.

The merge needs to add some safety checks to ensure that there aren't any duplicates when the permission assignment occurs, or otherwise just discard the erroneous new permissions maybe (since they're already covered by the existing ones)

**Comment by nthieberger** [comment] 2015-05-06 04:42
so what is to be done? Find the item that has the permissions issue and change it, then try the merge. again?

**Comment by nthieberger** [comment] 2015-05-06 04:45
ok, tried that and it worked. But it relies on us knowing where the conflict occurred, usually not the case. Is there any way of easily generating a validation error that the user can use to fix the problem?

**Comment by JonoGillett** [comment] 2015-05-06 04:48
Sorry Nick, I meant that comment more as a help for whoever works on a fix. Since by the time it gets looked at your initial error might be hard to find.
It should certainly be possible to sort this out at a code level automatically (I believe).

Either that or, as you say, generate a message that points the end user at the relevant record with guidance to fix.

**Comment by nthieberger** [comment] 2017-09-04 09:25
I just tried merging users and it failed

**Comment by nthieberger** [comment] 2018-02-16 04:30
Workaround is to assign collections to one user and delete the other one

**Closed by nthieberger** 2018-02-16 04:30 UTC
Labels: Bug
