### ISSUE TITLE
bug - adding new items to collections

### ISSUE THREAD

**Issue by AmandaPDSC** [nabu-catalog/nabu#403] opened 2015-02-05 04:32 UTC
Regular users can only add items to collections for which they have edit access if an administrator has already added 1 item. Users with edit access should be able to add items to a collection with no items

**Comment by JonoGillett** [comment] 2015-06-04 05:04
Hi Amanda,

I've tried a few different ways, but I'm unable to reproduce this behaviour. Perhaps it wasn't just related to adding a new item, but some other factor on the collection or item.

To help diagnose the problem could you tell me which collection you were working with? Also what sort of output/behaviour did you see when this occurred - was there an error?

Cheers,
Jono

**Comment by AmandaPDSC** [comment] 2015-06-04 05:14
It was TH2 - the collector was able to add new items to his collection TH1, but not to TH2 which had no items. Once I added one item, he could add more.
I'm not sure if he got an error message...

**Comment by AmandaPDSC** [comment] 2015-08-21 06:32
have not assigned this a priority since it seems the problem couldn't be replicated.

**Comment by agrimmtt** [comment] 2016-03-23 01:09
The user involved seemed to have problems with viewing the collection, let alone adding items.

    Started GET "/collections/TH2/items/new" for [IP address] at [DateStamp January 2015] +1100
    Processing by ItemsController#new as HTML
      Parameters: {"collection_id"=>"TH2"}
    Redirected to http://catalog.paradisec.org.au/
    Completed 302 Found in 21.0ms (ActiveRecord: 0.6ms)

    Started GET "/collections/TH2" for [IP address] at [DateStamp January 2015] +1100
    Processing by CollectionsController#show as HTML
      Parameters: {"id"=>"TH2"}
    Redirected to http://catalog.paradisec.org.au/
    Completed 302 Found in 25.1ms (ActiveRecord: 1.0ms)

    Started GET "/collections/TH3" for [IP address] at [DateStamp January 2015] +1100
    Processing by CollectionsController#show as HTML
      Parameters: {"id"=>"TH3"}
    Redirected to http://catalog.paradisec.org.au/
    Completed 302 Found in 24.7ms (ActiveRecord: 0.9ms)

This seems to be a general permissions problem rather than a bug with a particular page or action. That problem may have been independently fixed since then.

@AmandaPDSC is it ok to close this issue?

**Comment by AmandaPDSC** [comment] 2016-03-23 21:16
ok, well i haven't seen the issue replicated since then, so I suppose we can close it

**Comment by agrimmtt** [comment] 2016-04-03 23:31
Closing as per Amanda's comment.

**Closed by agrimmtt** 2016-04-03 23:31 UTC
Labels: waiting-for-feedback
