### ISSUE TITLE
bulk update failed

### ISSUE THREAD

**Issue by nthieberger** [nabu-catalog/nabu#515] opened 2016-01-04 06:50 UTC
Trying to bulk update ZF1 failed.

**Comment by agrimmtt** [comment] 2016-01-04 06:51
Deploying a new version is currently in progress. That's probably what
caused the problem.

Andrew

On 4 January 2016 at 17:50, nthieberger <notifications@github.com> wrote:

> Trying to bulk update ZF1 failed
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nabu-catalog/nabu/issues/515>.
>



-- 
*Andrew Grimm, **Software Engineer*
Terem Technologies

(p) 02 8035 3401
(m) 0403 827 562
(e) andrew.grimm@terem.com.au
(w) terem.com.au

Level 5, 90 Pitt St, Sydney NSW 2000.

This email and any files transmitted with it are confidential and intended
solely for the use of the individual or entity to whom they are addressed.

**Comment by agrimmtt** [comment] 2016-01-04 06:52
Deploying a new version is currently in progress. That's probably what caused the problem.

**Comment by nthieberger** [comment] 2016-01-11 19:30
Just tried a bulk update again and it failed (LG1, change all  'ready for metadata export' to true)

**Comment by nthieberger** [comment] 2016-01-12 03:09
Just did it again and it worked (DAL002 set 'ready for metadata export' to true). Using Safari on a mac

**Comment by nthieberger** [comment] 2016-01-13 20:22
Just succeeded in a bulk update of LG1 by selecting a subset of only 51 items rather than all 224 items that throw an error.

**Comment by agrimmtt** [comment] 2016-01-13 21:55
The bug should be fixed when the next version is deployed. The bug is probably caused by an item containing a comment with a non-existent owner.

**Comment by agrimmtt** [comment] 2016-01-22 06:54
Should be fixed by today's deployment.

**Closed by agrimmtt** 2016-01-22 06:54 UTC
Labels: 2016 Priorities, Awaiting deployment, Bug, Urgent (#1)
