### ISSUE TITLE
mp3 not downloading

### ISSUE THREAD

**Issue by LindaBarwick** [nabu-catalog/nabu#614] opened 2017-02-09 05:25 UTC
I can download other files in this item, but the following won't play or download

http://catalog.paradisec.org.au/repository/CLC/JL001/CLC-JL001-A.mp3

**Comment by LindaBarwick** [comment] 2017-02-09 05:36
Everything in NABU seems superslow at the moment, is it a more general problem?
@JonoGillett

**Comment by LindaBarwick** [comment] 2017-02-09 14:27
I was able to download large WAV files with no problems other than slowness but the mp3s that did copy down were zero KB and would not play. I was able to locate them elsewhere so the immediate issue has passed but it would be good to test this out with mp3 in other collections to see whether there is an issue.

**Comment by JonoGillett** [comment] 2017-02-09 22:48
@LindaBarwick I have taken a look at the file in question and can't find anything wrong with it specifically, however I am also unable to download it. No errors are reported in the logs so I will have to dig deeper to see if I can work out why.

If you need access to files before the issue is resolved, feel free to email me and I can retrieve them directly from the server.

**Comment by jodiekell** [comment] 2017-02-10 00:38
@LindaBarwick @JonoGillett I am having the same issue with the files in the DD1-003 and DD1-004. Both the MP3 and WAV files will not play or download.

**Comment by juliamiller** [comment] 2017-02-13 00:22
I have also been having problems accessing files in the catalog. Also, Louise Baird (LRB) tried to take a look at a text file  (LRB3-lexicon_texts-Lakbungblor.txt), but had some issues. It took a LONG time to download, then when it did download, the file was 0kb. File metadata says it should be 77.5 KB. I tried and got the same results. I then connected to NABU via Filezilla to see if I could download a copy from the catalog itself, but that file was also downloading a 0KB file, despite the file metadata indicating otherwise. @JonoGillett @LindaBarwick

**Comment by JonoGillett** [comment] 2017-02-13 02:57
@juliamiller @LindaBarwick @jodiekell I have investigated this issue and unfortunately nothing I can see indicates the cause of this problem. My belief is that there is some issue in the connection between the Nabu server and the file server which actually hosts the catalog - I have sent through an email recommending that the uni infrastructure team be contacted for help.

**Comment by LindaBarwick** [comment] 2017-02-14 00:23
As of this morning it seems to be working ok from here in Sydney. @juliamiller could you test from ANU please?

It would be good to know why it worked.

**Comment by juliamiller** [comment] 2017-02-14 01:54
Yes! All fully functional now!

**Comment by JonoGillett** [comment] 2017-02-14 01:58
As it seems like this was an infrastructure issue which is now resolved, can we close this ticket? @LindaBarwick

**Closed** 2017-02-14 02:30 UTC
Labels: Urgent (#1)
