### ISSUE TITLE
Invert searches, modify found sets

### ISSUE THREAD

**Issue by nthieberger** [nabu-catalog/nabu#589] opened 2016-06-17 23:27 UTC
It would be great to be able to invert searches, remove some items from a search, add two searches together etc. Referenced in the thread for #106

The issue is really that we can't create search sets, and then add and subtract things to/from the set. Is there a way to do this without completely overhauling the way the data is stored and searched?

We have a collection that needs to have certain text appended to the comments field, but only for a subset of that collection. At present we have no way of doing so, thus we have to edit each record individually.

**Comment by baristuncay** [comment] 2016-10-27 04:25
Dupe of https://github.com/nabu-catalog/nabu/issues/588 ?

**Comment by nthieberger** [comment] 2017-02-14 00:35
We need both 588 and 589 resolved so that searches and working with found sets can be more efficient

**Comment by nthieberger** [comment] 2017-04-04 01:08
Once we are more adept at using the new finding system we can revisit the possibility of merging and inverting found sets

**Comment by JonoGillett** [comment] 2018-02-16 03:41
The ability to remove individual results from a found result set has already been deployed.

**Closed** 2018-02-16 03:41 UTC
Labels: 2017 Priorities, Urgent (#1), search
