### ISSUE TITLE
Search for 'not'

### ISSUE THREAD

**Issue by nthieberger** [nabu-catalog/nabu#588] opened 2016-06-17 23:25 UTC
ability to find 'not' something

**Comment by baristuncay** [comment] 2016-10-27 04:25
Dupe of https://github.com/nabu-catalog/nabu/issues/589 ?

**Comment by AmandaPDSC** [comment] 2016-12-09 05:59
This is particularly relevant for the true/false searches. For example as search on ASMPI collection for 'metadata ready' true - produces 215 results, but false produces none, even though there are 242 items in the collection. A false search should produce results where yes is not ticked for 'metadata ready'

**Comment by JonoGillett** [comment] 2018-02-16 03:39
The above 'metadata ready' difference is potentially related to the issue mentioned in #633

**Closed** 2018-02-16 03:52 UTC
Labels: 2017 Priorities, Urgent (#1), search
