### ISSUE TITLE
Set map from country fails

### ISSUE THREAD

**Issue by AmandaPDSC** [nabu-catalog/nabu#453] opened 2015-07-28 06:33 UTC
Editing MR1-004 and MR1-043 I tried to set map from language and received the error that no map data was available. When I now try to set map from country (to restore what it had previously been set to - PNG) nothing happens.

**Comment by AmandaPDSC** [comment] 2015-08-10 02:58
Also MR1-094

**Comment by agrimmtt** [comment] 2015-09-17 02:30
Hi @AmandaPDSC . I've made three changes to solve this, all available on staging:

* Add no map match message to collections, as well as to items. That's so that when the boundaries aren't changed on that page, users will know why.
* Make the no map match message more specific. That's so that when someone tries both setting by country, and by language, they'll get changing error messages. That indicates that the website itself is at least trying to fulfill their request, rather than there being a bug in the website.
* Don't change boundaries when there is no boundary information.

Let me know if this fixes the problem.

**Comment by AmandaPDSC** [comment] 2015-11-20 05:11
Something funny going on with maps today: I've just been editing VKS-107_79, which previously had map data, but when I saved my edit, the map data disappeared and now set map by country isn't working.

**Comment by agrimmtt** [comment] 2015-11-20 05:32
@AmandaPDSC oddly enough, if you go to http://catalog.paradisec.org.au/collections/VKS/items/107_79/edit , it displays map information.

Looking at the database, it looks like no map information has been set for the item or the collection.

**Comment by AmandaPDSC** [comment] 2015-11-20 05:37
yes - exactly!

**Comment by agrimmtt** [comment] 2015-11-20 06:47
I think the problem is caused by its north limit being exactly zero degrees. Currently, if either the north limit, the south limit, the east limit, or the west limit are zero degrees, the program thinks the location information is missing.

I anticipate changing the logic such that all four have to be zero for it to be treated as missing, but not today.

The good news is that the data currently has the correct coordinate information in the database (I was mistaken about it not being in the database), it's just not being displayed.

**Comment by nthieberger** [comment] 2015-12-17 01:02
Still a problem. I just tried setting the map from the country (http://catalog.paradisec.org.au/collections/VKS/items/149_20) and it did nothing. I set the map by hand.

**Comment by agrimmtt** [comment] 2016-01-13 00:26
Resolved by the deployment made on Monday 4 January.

**Closed by agrimmtt** 2016-01-13 00:26 UTC
Labels: 2016 Priorities, Urgent (#1)
